name: solution-checker

on:
  workflow_dispatch:
    inputs:
      request_id:
        description: 'id of the request to worked on from Power Platform'
        required: false
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
      solution_version:
        description: 'version of the solution to worked on from Power Platform'
        required: true
      solution_exported_folder:
        description: 'folder name for staging the exported solution'
        required: true
        default: solutions/
      check_exported_folder:
        description: 'folder name for staging the exported check'
        required: true
        default: checks/        
env:
  ENVIRONMENT_URL: 'https://ava-powerplatform-dev.crm.dynamics.com'
  CLIENT_ID: '03f7f8a4-7b34-4f76-8c12-90a1565ca4fb'
  TENANT_ID: 'd7f2ff81-6d1b-4b31-a5f4-806476fd7131'
  
permissions:
  contents: write
jobs:
  checker-from-dev:
    runs-on: windows-latest

    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip
        run-asynchronously: true
        overwrite: true
        
    - name: check-solution action
      uses: microsoft/powerplatform-actions/check-solution@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        path: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip
        checker-logs-artifact-name: ${{ github.event.inputs.checks_folder }}
        
    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: ${{ github.event.inputs.solution_target_folder}}/${{ github.event.inputs.solution_name }}
        solution-target-folder: ${{ github.event.inputs.solution_target_folder}}/${{ github.event.inputs.solution_name }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
