name: solution-checker

on:
  workflow_dispatch:
    inputs:
      request_id:
        description: 'id of the request to worked on from Power Platform'
        required: false
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
      solution_exported_folder:
        description: 'folder name for staging the exported solution'
        required: true
        default: solutions/      
env:
  ENVIRONMENT_URL: 'https://ava-powerplatform-dev.crm.dynamics.com'
  CLIENT_ID: '03f7f8a4-7b34-4f76-8c12-90a1565ca4fb'
  TENANT_ID: 'd7f2ff81-6d1b-4b31-a5f4-806476fd7131'
  
permissions:
  contents: write
jobs:
  checker-from-dev:
    runs-on: ubuntu-latest

    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
        
    - name: check-solution action
      uses: microsoft/powerplatform-actions/check-solution@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        path: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip

    - name: ls 
      run: |
        ls /home/runner/work/_temp/PowerAppsChecker/checker-output
        
    - name: extract-checker-results
      id: extract-checker-results
      run: |
        CHECKER_RESULTS=$(grep -oP 'Results : \K.*' /home/runner/work/_temp/PowerAppsChecker/checker-output/*.log)
        echo "checker_results=$CHECKER_RESULTS" >> $GITHUB_ENV

    - name: download-checker-results
      run: |
        echo "Downloading checker results from: ${{ env.checker_results }}"
        
    - name: commit 
      run: |
        git fetch --all 
        git config --global user.email "no-reply@github.com"
        git config --global user.name "GitHub Actions"
        git add --all 
        git commit -m "Exported solution ${{ github.event.inputs.solution_name }} at $(TZ=America/Sao_Paulo date +'%d/%m/%Y %H:%M:%S')"
        git push
