name: solution-checker

on:
  workflow_dispatch:
    inputs:
      request_id:
        description: 'id of the request to worked on from Power Platform'
        required: false
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
      solution_exported_folder:
        description: 'folder name for staging the exported solution'
        required: true
        default: solutions/      
env:
  ENVIRONMENT_URL: 'https://ava-powerplatform-dev.crm.dynamics.com'
  CLIENT_ID: '03f7f8a4-7b34-4f76-8c12-90a1565ca4fb'
  TENANT_ID: 'd7f2ff81-6d1b-4b31-a5f4-806476fd7131'
  
permissions:
  contents: write
jobs:
  checker-from-dev:
    runs-on: ubuntu-latest

    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    - name: install-power-platform-tools action
      uses: microsoft/powerplatform-actions/actions-install@v1 
      
    - name: check-solution action
      id: powerapps-checker
      uses: microsoft/powerplatform-actions/check-solution@v1
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        path: ${{ github.event.inputs.solution_exported_folder }}/${{ github.event.inputs.solution_name }}.zip

    - run: echo "Solution Checker ${{ steps.powerapps-checker.outputs }}"
      
    - name: commit 
      run: |
        git fetch --all 
        git config --global user.email "no-reply@github.com"
        git config --global user.name "GitHub Actions"
        git add --all 
        git commit -m "Exported solution ${{ github.event.inputs.solution_name }} at $(TZ=America/Sao_Paulo date +'%d/%m/%Y %H:%M:%S')"
        git push
