name: export-and-branch-solution

on:
  repository_dispatch:
    types: [export-solution]
    
env:
  ENVIRONMENT_URL: 'https://ava-powerplatform-dev.crm.dynamics.com'
  CLIENT_ID: '03f7f8a4-7b34-4f76-8c12-90a1565ca4fb'
  TENANT_ID: 'd7f2ff81-6d1b-4b31-a5f4-806476fd7131'
  WORKFLOW_URL: 'https://prod-62.westus.logic.azure.com:443/workflows/b228d7d3e3784e2abed7359a8902b901/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=Kaoklk6L_8Xtxbq8kPVK639yDYCKWoI6cy0dUGjOPsE'
  RUN_KEY: 'FSgWPsAEBDP6epQZ'
permissions:
  contents: write
jobs:
  export-from-dev:
    runs-on: ubuntu-latest

    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
    
    - name: Log Start Export Solution
      run: |
        curl -X POST "${{env.WORKFLOW_URL}}" \
        -H "Content-Type: application/json" \
        -H "RunKey: ${{env.RUN_KEY}}" \
        -d '{"request": "${{ github.event.client_payload.request_id }}","log": "Iniciando exportação da solução: ${{ github.event.client_payload.solution_name }}..."}'

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        solution-name: ${{ github.event.client_payload.solution_name }}
        solution-output-file: ${{ github.event.client_payload.solution_exported_folder}}/${{ github.event.client_payload.solution_name }}.zip

    - name: Log End Export Solution
      run: |
        curl -X POST "${{env.WORKFLOW_URL}}" \
        -H "Content-Type: application/json" \
        -H "RunKey: ${{env.RUN_KEY}}" \
        -d '{"request": "${{ github.event.client_payload.request_id }}","log": "Solução <b>${{ github.event.client_payload.solution_name }}</b> exportada."}'
        
    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: ${{ github.event.client_payload.solution_exported_folder}}/${{ github.event.client_payload.solution_name }}.zip
        solution-folder: ${{ github.event.client_payload.solution_folder}}/${{ github.event.client_payload.solution_name }}
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: Log End Unzip Solution
      run: |
        curl -X POST "${{env.WORKFLOW_URL}}" \
        -H "Content-Type: application/json" \
        -H "RunKey: ${{env.RUN_KEY}}" \
        -d '{"request": "${{ github.event.client_payload.request_id }}","log": "Solução <b>${{ github.event.client_payload.solution_name }}</b> descompactada."}'

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: ${{ github.event.client_payload.solution_folder}}/${{ github.event.client_payload.solution_name }}
        solution-target-folder: ${{ github.event.client_payload.solution_target_folder}}/${{ github.event.client_payload.solution_name }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true

    - name: Log End Prepare PullRequest
      run: |
        curl -X POST "${{env.WORKFLOW_URL}}" \
        -H "Content-Type: application/json" \
        -H "RunKey: ${{env.RUN_KEY}}" \
        -d '{"request": "${{ github.event.client_payload.request_id }}","log": "Solução <b>${{ github.event.client_payload.solution_name }}</b> preparada para Pull Request."}'
